# mongo db + redis
# Week 1: MongoDB + Redis only
# From this directory: docker compose up -d
services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017" #mongodb:127.0.0.1:27017
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.runCommand({ ping: 1 }).ok"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  mongo_data:
